spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://bj-cynosdbmysql-grp-p55yr6pq.sql.tencentcdb.com:29754/MSHD2?useSSL=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: syc
    password: syc123456!
  data:
    redis:
      database: 0
      host: 82.157.75.213
      lettuce:
        pool:
          max-active: -1
          max-idle: 0
          max-wait: -1ms
          min-idle: 0
        shutdown-timeout: 100ms
      port: 6379
      password: yy123456!
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#logging:
#  level:
#    com.bupt.mshd2_0boot.mapper: debug
server:
  port: 8077

file_path: "/root/MSHD_file/"

# others
GaodeKey: "e9e73ff0da55fd71b277287462d2dcc7" # 高德api的key
GaodeApiAddressCode: "https://restapi.amap.com/v3/config/district" # 高德api(行政区编码)
ConnectionTimeout: 5000 # 连接超时时间: 5s
SocketTimeout: 5000 # 读取超时时间：5s

pageSize: 20